name: node-js-test
description: node-js-test

# Composite action that enforces formatting/lint/test quality gates for Node.js
# packages. It installs dependencies, runs Prettier, lint, badges, and test
# scripts so consuming repos can mirror the CI workflow locally.

inputs:
  node-version:
    description: 'Node.js version to install via actions/setup-node'
    required: false
    default: '22'
  enable-cache:
    description: 'Enable npm dependency caching (requires package-lock.json)'
    required: false
    default: 'true'
  lint-script:
    description: 'npm script responsible for linting'
    required: false
    default: 'lint'
  prettier-script:
    description: 'npm script that runs Prettier in check mode'
    required: false
    default: 'format:check'
  badges-script:
    description: 'Optional npm script that refreshes README/coverage badges'
    required: false
    default: 'badges'
  test-script:
    description: 'npm script that executes the test suite'
    required: false
    default: 'test'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.enable-cache == 'true' && 'npm' || '' }}
      # Installs the requested Node version and optionally caches npm dependencies.

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail

        if [ ! -f package.json ]; then
          echo "::error::package.json not found in repository root."
          exit 1
        fi

        if [ -f package-lock.json ]; then
          echo "Using npm ci because package-lock.json is present."
          npm ci
          INSTALL_CMD="npm ci"
        else
          echo "No package-lock.json detected → falling back to npm install."
          npm install
          INSTALL_CMD="npm install"
        fi

        echo "- [x] $INSTALL_CMD" >> "$GITHUB_STEP_SUMMARY"
      # Uses npm ci (when available) for reproducible installs.

    - name: Run lint script
      shell: bash
      run: |
        set -euo pipefail
        SCRIPT="${{ inputs.lint-script }}"

        if [ -z "$SCRIPT" ]; then
          echo "::notice::Lint script input empty → skipping lint step."
          echo "- [ ] npm run (lint skipped)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts && Object.prototype.hasOwnProperty.call(pkg.scripts, '$SCRIPT') ? 0 : 1);"; then
          npm run "$SCRIPT"
          echo "- [x] npm run $SCRIPT" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "::error::package.json is missing an npm script named '$SCRIPT'. Override lint-script or leave it empty to skip."
          exit 1
        fi
      # Enforces lint parity via the configured npm script.

    - name: Run prettier script
      shell: bash
      run: |
        set -euo pipefail
        SCRIPT="${{ inputs.prettier-script }}"

        if [ -z "$SCRIPT" ]; then
          echo "::notice::Prettier script input empty → skipping formatting check."
          echo "- [ ] npm run (prettier skipped)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts && Object.prototype.hasOwnProperty.call(pkg.scripts, '$SCRIPT') ? 0 : 1);"; then
          npm run "$SCRIPT"
          echo "- [x] npm run $SCRIPT" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "::error::package.json is missing an npm script named '$SCRIPT'. Override prettier-script or leave it empty to skip."
          exit 1
        fi
      # Verifies Prettier formatting stays consistent.

    - name: Refresh badges
      shell: bash
      run: |
        set -euo pipefail
        SCRIPT="${{ inputs.badges-script }}"

        if [ -z "$SCRIPT" ]; then
          echo "::notice::Badge script input empty → skipping badge refresh."
          echo "- [ ] npm run (badges skipped)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts && Object.prototype.hasOwnProperty.call(pkg.scripts, '$SCRIPT') ? 0 : 1);"; then
          npm run "$SCRIPT"
          echo "- [x] npm run $SCRIPT" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "::error::package.json is missing an npm script named '$SCRIPT'. Override badges-script or leave it empty to skip."
          exit 1
        fi
      # Keeps README/coverage badges updated via a repo-defined script.

    - name: Run tests
      shell: bash
      run: |
        set -euo pipefail
        SCRIPT="${{ inputs.test-script }}"

        if [ -z "$SCRIPT" ]; then
          echo "::notice::Test script input empty → skipping tests."
          echo "- [ ] npm run (tests skipped)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts && Object.prototype.hasOwnProperty.call(pkg.scripts, '$SCRIPT') ? 0 : 1);"; then
          npm run "$SCRIPT"
          echo "- [x] npm run $SCRIPT" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "::error::package.json is missing an npm script named '$SCRIPT'. Override test-script or leave it empty to skip."
          exit 1
        fi
      # Executes the configured npm test script.
